name: Deploy MkDocs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install mkdocs-material pymdown-extensions mkdocs-mermaid2-plugin

      - name: Deploy site
        run: |
          mkdocs gh-deploy --config-file mkdocs/mkdocs.yml --force
